const USER_REGISTER = "USER_REGISTER";
const USER_LOGIN = "USER_LOGIN";
const USER_LOGOUT = "USER_LOGOUT";
const USER_DETAILS = "USER_DETAILS";
export { USER_REGISTER, USER_LOGIN, USER_LOGOUT, USER_DETAILS };
